Algoritmo "Digiteumnumero"

Var
numero:inteiro

Inicio
escreval("digite um  numero de 1 á 5:")
leia(numero)

se numero = 1 entao
  escreval("um")
senao
se numero=2 entao
  escreval("dois")
senao
se numero=3  entao
  escreval("três")
senao
se numero=4  entao
   escreval("Quatro")
senao
se numero=5 entao
  escreval("Cinco")
 senao
  escreval("NÚMERO INVÁLIDO")
fimse
fimse
fimse
fimse
fimse
Fimalgoritmo