Algoritmo "calculaidade"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// isso é um comentario e não é executado
Var
// Seção de Declarações das variáveis 
nome:caracter
anoNasc:inteiro
idade:inteiro


Inicio
escreval("digite seu nome completo:")
leia(nome)
escreval("digite seu ano de nascimento:")
leia(anoNasc)

idade<-2023-anoNasc

Escreval(nome," A sua idade é:",idade,"anos de idade")




Fimalgoritmo